name: Run E2E Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmqctl status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Wait for RabbitMQ and PostgreSQL to be ready
        run: |
          echo "Waiting for services to be ready..."
          sleep 20

      - name: Configure Application Properties
        run: |
          echo "spring.rabbitmq.host=localhost" > src/test/resources/application-test.properties
          echo "spring.rabbitmq.port=5672" >> src/test/resources/application-test.properties
          echo "spring.rabbitmq.username=guest" >> src/test/resources/application-test.properties
          echo "spring.rabbitmq.password=guest" >> src/test/resources/application-test.properties
          echo "spring.datasource.url=jdbc:postgresql://localhost:5432/testdb" >> src/test/resources/application-test.properties
          echo "spring.datasource.username=testuser" >> src/test/resources/application-test.properties
          echo "spring.datasource.password=testpass" >> src/test/resources/application-test.properties
          echo "spring.datasource.driver-class-name=org.postgresql.Driver" >> src/test/resources/application-test.properties

      - name: Build Project
        run: mvn clean package -DskipTests

      - name: Run E2E Tests
        run: mvn test -Dspring.profiles.active=test
